version: "3.5"
services:
  database:
    image: mongo:4.0.4
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  service:
    image: agranom/service-auth
    env_file:
      - ./../../.env
      - ./../config/local.env
    ports:
      - "3001:3001"
    restart: on-failure

volumes:
  mongodb:
  mongodb_config:
