version: "3.5"
networks:
  default:
    driver: bridge
services:
  database:
    image: mongo:4.0.4
    networks:
      - default
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  service:
    image: service-auth:latest
    networks:
      - default
    env_file:
      - ./../config/local.env
    ports:
      - "80:3001"
    restart: on-failure

volumes:
  mongodb:
  mongodb_config:
