version: "3.5"
networks:
  default:
    driver: bridge
services:
  database:
    image: mongo:4.0.4
    networks:
      - default
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  service:
    image: agranom/service-task
    networks:
      - default
    env_file:
      - ./../config/local.env
    ports:
      - "3000:3000"
    restart: on-failure

volumes:
  mongodb:
  mongodb_config:
